services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: vide_grenier_php_prod
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - network_prod
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: vide_grenier_db_prod
    restart: always
    env_file:
      - .env
    volumes:
      - db_data_prod:/var/lib/mysql
    networks:
      - network_prod

volumes:
  db_data_prod:

networks:
  network_prod:
    driver: bridge
