services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: vide_grenier_php_dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=NcpRV3Ugo9MOt
      - DB_NAME=vide_grenier_db_dev
    networks:
      - network_dev
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: vide_grenier_db_dev
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=NcpRV3Ugo9MOt
      - MARIADB_DATABASE=vide_grenier_db_dev
    volumes:
      - ./db_data_dev:/var/lib/mysql
    networks:
      - network_dev

networks:
  network_dev:
    driver: bridge
